export const Codes = {
  NAV_TIMEOUT: "NAV_TIMEOUT",
  BROWSER_CRASH: "BROWSER_CRASH",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  CAPTCHA_REQUIRED: "CAPTCHA_REQUIRED",
  LOGIN_FAILED: "LOGIN_FAILED",
  ROBOTS_DISALLOWED: "ROBOTS_DISALLOWED",
  ASSET_TOO_LARGE: "ASSET_TOO_LARGE",
  NODE_LIMIT: "NODE_LIMIT",
  PROJECT_SIZE_LIMIT: "PROJECT_SIZE_LIMIT",
  AI_RATE_LIMIT: "AI_RATE_LIMIT",
  AI_AUTH: "AI_AUTH",
  AI_BAD_CONFIG: "AI_BAD_CONFIG",
  AI_TOO_LARGE: "AI_TOO_LARGE",
  AI_BAD_RESPONSE: "AI_BAD_RESPONSE",
  AI_QUOTA: "AI_QUOTA",
  BUDGET_EXCEEDED: "BUDGET_EXCEEDED",
  IR_PATCH_INVALID: "IR_PATCH_INVALID",
  IR_VERSION_UNSUPPORTED: "IR_VERSION_UNSUPPORTED",
  GRAPH_NOT_FOUND: "GRAPH_NOT_FOUND",
  INSPECTOR_OP_FAILED: "INSPECTOR_OP_FAILED",
  AI_CIRCUIT_OPEN: "AI_CIRCUIT_OPEN",
  QUEUE_FULL: "QUEUE_FULL",
  PROJECT_BUSY: "PROJECT_BUSY",
  STALE_REVISION: "STALE_REVISION",
  DOCUMENT_MATERIALIZE_FAILED: "DOCUMENT_MATERIALIZE_FAILED",
  NOTHING_TO_UNDO: "NOTHING_TO_UNDO",
  NOTHING_TO_REDO: "NOTHING_TO_REDO",
} as const;

export type Code = keyof typeof Codes;

export class AppError extends Error {
  constructor(public code: Code, message: string, public context?: Record<string, unknown>) {
    super(message);
    this.name = "AppError";
  }
}
