// Generates src/app/_ui/icons.gen.ts: the Material Symbols Outlined paths (viewBox 0 -960 960 960) of the icons the UI uses
// (spec parity §1.5), from the @material-symbols/svg-400 devDependency (Apache-2.0). The output is committed, so a build
// needs neither the network nor this script. A name missing from the package exits 1. Run: npm run icons
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

// Names as in the mockups' data-icon.
export const NAMES = [
  // shell / nav
  "history", "add", "settings", "timeline", "account_tree", "difference", "edit", "code",
  // common
  "search", "refresh", "open_in_new", "content_copy", "visibility", "visibility_off", "expand_more", "chevron_right",
  "chevron_left", "close", "check", "remove", "more_vert", "arrow_forward", "undo", "redo", "save",
  // editor Component panel (E2 §7: keyboard reorder)
  "arrow_upward", "arrow_downward",
  // status
  "check_circle", "cancel", "pause_circle", "warning", "lock", "error", "schedule", "draft",
  // project actions
  "pause", "play_arrow", "replay", "delete", "download", "folder_zip", "drive_folder_upload", "bolt", "hub", "add_circle", "block",
  // /new
  "language", "radar", "generating_tokens", "output",
  // stepper
  "task_alt", "photo_camera", "image", "schema", "badge", "auto_fix_high",
  // preview
  "phone_iphone", "tablet_mac", "desktop_windows", "view_column_2", "opacity", "compare", "layers",
  // code viewer
  "folder", "folder_open", "description", "html", "css", "javascript", "data_object", "format_list_numbered", "wrap_text",
  // visual editor E3a (layer tree types, upload)
  "title", "link", "touch_app", "input", "movie", "shapes", "widgets", "crop_square", "upload",
  // visual editor E3b (zoom)
  "zoom_in", "zoom_out", "fit_screen",
  // sitemap
  "unfold_more", "unfold_less",
];

// Ligature aliases the package ships under the glyph's current file name.
export const FILE_OF = { expand_more: "keyboard_arrow_down", phone_iphone: "mobile", auto_fix_high: "wand_stars", generating_tokens: "token" };

function main() {
  const root = join(dirname(fileURLToPath(import.meta.url)), "..");
  const dir = join(root, "node_modules", "@material-symbols", "svg-400", "outlined");
  const lines = [];
  for (const name of NAMES) {
    const file = join(dir, `${FILE_OF[name] ?? name}.svg`);
    let svg;
    try {
      svg = readFileSync(file, "utf8");
    } catch {
      console.error(`gen-icons: "${name}" not found (${file})`);
      process.exit(1);
    }
    const d = [...svg.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]).join(" ");
    if (!d) {
      console.error(`gen-icons: no <path d> in ${file}`);
      process.exit(1);
    }
    lines.push(`  ${name}: ${JSON.stringify(d)},`);
  }
  const out = [
    "// GENERATED by scripts/gen-icons.mjs from @material-symbols/svg-400 (Apache-2.0). Do not edit: npm run icons.",
    "export const ICONS = {",
    ...lines,
    "} as const;",
    "export type IconName = keyof typeof ICONS;",
    "",
  ].join("\n");
  writeFileSync(join(root, "src", "app", "_ui", "icons.gen.ts"), out);
  console.log(`gen-icons: ${NAMES.length} icons`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
